# Generated by Django 4.2.7 on 2024-02-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('order_notes', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='medicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('medicine_name', models.CharField(max_length=50)),
                ('prescription', models.ImageField(upload_to='prescriptions/')),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharm_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('expiry_date', models.DateField()),
                ('provider_status', models.BooleanField(blank=True)),
                ('medication_route', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.store')),
            ],
        ),
    ]
