# Generated by Django 4.2.7 on 2024-01-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latex_free_status',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='medication_route',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='provider_status',
            field=models.BooleanField(blank=True),
        ),
    ]
