# Generated by Django 4.2.7 on 2024-02-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=255, verbose_name='Doctor Name')),
                ('d_mobile', models.CharField(max_length=15, verbose_name='Doctor Contact Number')),
                ('d_qualification', models.CharField(max_length=255)),
                ('d_specialist', models.CharField(max_length=255)),
                ('d_yoe', models.CharField(max_length=2, verbose_name='Year Of Experience')),
                ('remaining', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=255, verbose_name='Doctors Available')),
                ('time_slot', models.CharField(max_length=255, verbose_name='Timing')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='Patient.doctor', verbose_name='Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_made_on', models.DateField(auto_now_add=True, verbose_name='Appointment Booking Date')),
                ('app_fix_date', models.DateField(blank=True, verbose_name='Appointment Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Patient.doctor', verbose_name='Doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='Patient.customuser', verbose_name='Patient')),
            ],
        ),
    ]
